#!/bin/sh
# Script to run bookmarks in 'New Window'
# Aug 28 - 2019

bookmarks=/home/$USER/.bookmarks
LABURLS=/home/$USER/.laburls
url=$(sort $bookmarks | sed s/@.*// | dmenu -i -p "Select a Bookmark" | xargs -I % grep "%@" $bookmarks | sed s/.*@//)


if [[ $url == *"Lab"* ]]
then
	xargs -a $LABURLS $BROWSER -new-window "$line"
else
	$BROWSER -new-window $url
fi
