#!/bin/bash
# Script to open All book marks - one at a time or all together.
# .bookmarks saved as 'Alias@https://url.com'
# Dmenu Selection 'All' opens all bookmarks

bookmarks=/home/$USER/.bookmarks

declare -A address
while IFS='@' read -r name add
do
    address[$name]=$add
    echo "$name - ${address[$name]}"
done < "$bookmarks"

for name in "${!address[@]}"
do
    echo "$name - ${address[$name]}"
done

selection=$(printf '%s\n' All "${!address[@]}"| dmenu -i -p "Select a Bookmark")

addy=${address[$selection]}

#
if [[ "$selection" == *"All"* ]]; then
args=(); for url in "${address[@]}"; do args+=(-new-tab -url "$url"); done; "$BROWSER" "${args[@]}"

else
	"$BROWSER" -new-tab "$addy"
fi
