#!/bin/sh
# Script to launch bookmarks 'New-window'
# When you select 'Lab' via dmenu it will open $LABURLS in the browser each on it's own tab in a new window
# Otherwise it will open the selected $URL in a new-window
# .bookmarks entries should be one per line and should go alias "@" url "Google@https://google.com"
# Aug 28 2019

bookmarks=/home/$USER/.bookmarks
LABURLS=/home/$USER/.laburls
url=$(sort $bookmarks | sed s/@.*// | dmenu -i -p "Select a Bookmark" | xargs -I % grep "%@" $bookmarks | sed s/.*@//)


if [[ $url == *"Lab"* ]]
then
	xargs -a $LABURLS $BROWSER -new-window "$line"
else
	$BROWSER -new-window $url
fi
